kind: ConfigMap
apiVersion: v1
metadata:
  name: eap-config
data:
  eap-config.cli: |-
    /subsystem=logging/logger=org.wildfly.demo:add(level=DEBUG)
    /subsystem=logging/console-handler=CONSOLE:write-attribute(name=level, value=DEBUG)
